project:
  type: website
  output-dir: docs

book:
  title: "CASA00025 Group Project"
  author: "SQLMister group"
  date: "27/04/2025"
  chapters:
    - index.qmd
    
Grape Cultivation Analysis Toolkit

  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: casa_logo.png



format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
